### ISSUE TITLE
Discord link goes to Winthemers instead of Hyper discord server?

### ISSUE THREAD

**Issue by medievalberries** [nodgear/Hyperbar#1]

**Comment by nodgear** [comment]
We didn't had a discord link before, and hyper was getting some attraction, so i pointed to winthemers.
The current branch is the pre-release one, which has no read-me at all.
I'll change the master branch soon.

**Comment by medievalberries** [comment]
I assumed you just hadn't updated it, I was just m=aking sure you knew. Glad you're on top of it
