### ISSUE TITLE
Invalid links in the readme

### ISSUE THREAD

**Issue by charliie-dev** [nodgear/Hyperbar#10]
I find most of the links in the readme are invalid, maybe u put the wrong links?

**Comment by nodgear** [comment]
No, the machine i used to host those images are now gone.
After a power surge destroyed my SSD i lost most of the work i hade done on hyper and dropped the project due to lack of time, meaning i haven't really started the project to take new screenshots.

**Comment by charliie-dev** [comment]
Sorry about the bad news... 
Lost data is the last thing everyone would want to encounter.
